name: SFS CI Deploy
on:
  push:
    branches:
      - main
      - chore/enable-sfs-ci-*
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  call-sfs:
    uses: smartflow-systems/SmartFlowSite/.github/workflows/sfs-ci-deploy.yml@main
    secrets: inherit
